version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocketworlds
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379?protocol=resp3
      - MONGODB_URL=mongodb://mongo:27017
      - PORT=3000
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - /init.js:/docker-entrypoint-initdb.d/init.js:ro
    restart: unless-stopped

volumes:
  mongo-data:
